on:
  release:
    types:
      - published

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/upload-artifact@v2
        with:
          name: agent-template-python-${{ github.sha }}
          path: src

  release:
    needs:
      - package
    permissions:
      contents: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        extension:
          - zip
          - tar.gz
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v3
        with:
          name: agent-template-python-${{ github.sha }}
          path: agent-template-python/src

      - run: |
          cp CHANGELOG.md LICENSE README.md agent-template-python/

      - name: Pack artifact (zip)
        if: startsWith(matrix.extension, 'zip')
        run: |
          zip -r agent-template-python.zip agent-template-python/*

      - name: Pack artifact (tar)
        if: startsWith(matrix.extension, 'tar')
        run: |
          tar -czvf agent-template-python.tar.gz agent-template-python/*

      - name: Upload artifact to release
        uses: softprops/action-gh-release@v1
        with:
          append_body: true
          files: |
            agent-template-python.${{ matrix.extension }}
